INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Mary', 'Complete assignment', CURRENT_DATE, FALSE);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'John', 'Complete work', CURRENT_DATE, FALSE);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Helen', 'Learn React', CURRENT_DATE, FALSE);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Mark', 'Leetcode', CURRENT_DATE, FALSE);